server:
  port: 8081

spring:
  application:
    name: &app-name passenger-service

  datasource:
    url: jdbc:postgresql://localhost:5440/passengers_db
    username: aleshkey
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master-passenger.xml
